name: Comment based on issue content

on:
  issues:
    types:
      - opened

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write  # 给 workflow 添加对 issues 的写权限，确保可以评论

    steps:
      # Step 1: Checkout repository (ensure the repository is cloned)
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Extract the issue body (content of the issue)
      - name: Extract issue content
        id: issue_content
        run: |
          echo "ISSUE_TITLE=${{ github.event.issue.title }}" >> $GITHUB_ENV
          echo "ISSUE_BODY=${{ github.event.issue.body }}" >> $GITHUB_ENV

      # Step 3: Run custom script with the issue content
      - name: Run script to decide reply content
        id: decide_reply
        run: |
          # Save the issue title and content into a file for the script
          echo "Title: ${{ env.ISSUE_TITLE }}" > issue_info.txt
          echo "Content: ${{ env.ISSUE_BODY }}" >> issue_info.txt
          
          # Call your custom script here (you can replace this with your script)
          python3 ./scripts/response_issue.py issue_info.txt 

      # Step 4: Add comment based on the script output
      - name: Add comment to the issue
        run: |
          COMMENT=$(cat reply_content.txt)  # Assume your script writes the reply to this file
          gh issue comment ${{ github.event.issue.number }} --body "$COMMENT"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.decide_reply.outputs.reply_needed == 'true' }}
